### ISSUE TITLE
New abusers (Steemit Defense League)

### ISSUE THREAD

**Issue by MWFIAE** [steemit/redeemer-irredeemables#19]
Hello please add the following users to the list.

dernu
treedain
jetenculeprofond
magasintop1

They flagged me because I upvoted steemcleaners in the past. They profils do link to "justpaste" where they do explain that. Also they are operating only on the delegated power of steemit. 

Thanks a lot! :) 

PS: No harm was done as they only downvoted my post which was older than 7 days, but they surely are a problem for newer users and people who post more regularly 😉

**Comment by jredbeard** [comment]
looks like these were added to the list with a previous PR - thanks

**Comment by networkallstar** [comment]
Hi guys, here are fresh camillesteemer accounts. Greetings, Tom

@rezaturi
@deito
@zerbo
@grenai
@yaluma
@jertrasoim
@vikeazim
@termium
@viazer
@ferclua
@lubrice
@dreiml
@atouir
@sefuki
@amigaju
@krarimba
@maquil
@jolerus
@vrikoplo
@trimesgi
@tulber
@firgsia
@drisod
@hiluop
@drimne
@arginexumu
@supirsui
@hushcasi
@oliviza
@trouzi
@vetun
@paraloi
@hupolitre
@mangilop
@bleerer
@molcli
@timultid
@sibella
@giuvre
@jirtrumi
@tigirl
@a-alphasteem
@charlesdeherstal
@hilonrima
@hatshep
@verunick
@raclim
@renyd
@grimairt
@zizisasa
@giobarco
@hilonrima
@clavna
@criblo
@sergiom2
@gretycash
@jossefa
@hyjuki
@sasdemise
@jurtif
@facresil
@twosmin
@farouda
@droilzie
@xezagu
@tygewer
@serza
@crameso
@rezsad
@servtiom
@supec
@orvilam
@jusard
@xercu
@roadang
@minchew
@jestru
@lalihe
@krepiev
@xujik
@vramul
@trywest
@warzi
@castol
@drelist
@vrebui
@muiden
@triklu
@brillon
@cissel
@drelist
@crapal
@hipla
@xirro
@qitrulle
@likredu
@modranmi
@fabriol
@lokust
@socomore
@morfike
@zanze
@vramul
@trywest
