### ISSUE TITLE
Suggested Name Change

### ISSUE THREAD

**Issue by rakkasan84** [steemit/redeemer-irredeemables#4]
While "deplorable" _may_ have been a good descriptor for certain bad actors on steemit in the past, it now seems to be a term used to descibe non-Hillary voters in the US election. Describing a group of people as deplorables may lead to some confusion especially for US members. On a blockchain that is supposed to be censorship free, I don't see how keeping lists like these is any better than what Twitter, YouTube, and the others are doing by shadowbanning and otherwise making their content less visible. Suggested change to: Spammers and Scammers

Taken from Urban Dictionary:
Deplorables
Noun referring to the group of low-life, die-hard Donald Trump supporters who are on the fringes of society, like racist KKK members who support Trump. Hillary Clinton came up with this description, which seems to have stuck.

Now this same group of swamp-dwelling skinheads are no longer offended by the term, now they proudly refer to themselves as "deplorables". Think of the way some people proudly embrace calling themselves hillbilly or red-neck or trailer trash, and now deplorables.

**Comment by jnordberg** [comment]
> On a blockchain that is supposed to be censorship free, I don't see how keeping lists like these is any better than what Twitter, YouTube, and the others are doing by shadowbanning and otherwise making their content less visible.

This has nothing to do with censorship. This is a community curated list of users that are likely to be spammers and the private entity Steemit Inc. chooses to withdraw its delegation (a.k.a. interest-free loan) from them.

**Comment by jnordberg** [comment]
Name has now been changed to `redeemer-irredeemables`, don't tell Hillary!
